# Generated by Django 5.0.6 on 2024-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nr_cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
