# Generated by Django 5.0.6 on 2024-06-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_nr_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='nr_placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
